### PR TITLE
Added num_steps for AsyncProcess as well as ability to GET/SET Var wh…

### PR DESCRIPTION
**Pull request by ysingh7**
…en its not in RUNNING State.

Issue Number: 

Objective of pull request:

## Pull request checklist

Your PR fulfills the following requirements:
- [ ] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
- [ ] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [ ] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
- [ ] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
- [ ] Build tests (`pytest`) passes locally

## Pull request type

 

 

Please check your PR type:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe): 

## What is the current behavior?

-

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by awintel** [comment]
What's the intention here?
num_steps + AsyncProc looks a bit like a hack as an AsyncProc does not have a notion of time.
If this is necessary short term, have you filed another story to resolve the root cause requiring this hack?

**Comment by bamsumit** [comment]
> What's the intention here? num_steps + AsyncProc looks a bit like a hack as an AsyncProc does not have a notion of time. If this is necessary short term, have you filed another story to resolve the root cause requiring this hack?

@awintel The intention of the `num_steps` is to communicate how many timesteps the model is intended to run. I do understand that it is not absolutely necessary and the Async Model does not need to use it. This additional information of `num_steps`
* provides a way to stop the async model execution after the intended timestep. 
* makes get/set vars at the end of the execution possible.
* allows us to dynamically convert models using Loihi protocol to Async which will speed up the lava inference.

**Review by bamsumit — APPROVED** [review]

**Comment by awintel** [comment]
Ok thanks.
I'm not against doing this in the short term. But we should revise this architectural awkwardness.

**Comment by ysingh7** [comment]
> Ok thanks. I'm not against doing this in the short term. But we should revise this architectural awkwardness.

@awintel I have created an issue to track this : https://github.com/lava-nc/lava/issues/592.

**Review by joyeshmishra — APPROVED** [review]

**Pull request merged**
