### PR TITLE
Making my fork diff clean: 0 (zero) files change in this PR

### PR DESCRIPTION
**Pull request by srrisbud**
Creating this PR just to make srrisbud/lava:main diff clean with respect to lava-nc/lava:main. There is only a difference in commit history and no files change through this PR.

### CODE REVIEW

**Review by phstratmann — DISMISSED** [review]

**Comment by mgkwill** [comment]
Why are you doing this? I don't understand.

If this only concerns your fork there are other ways to clean up other than opening a pull against lava main.

**Comment by srrisbud** [comment]
> Why are you doing this? I don't understand.
> 
> If this only concerns your fork there are other ways to clean up other than opening a pull against lava main.

How do I do this? In my fork, I see that "fetch upstream" button is disabled, because there is nothing to fetch. The file contents are identical between lava-nc/lava:main and my fork srrisbud/lava:main.

But my fork's commits are slightly different. They diverged when I fixed the lava -> src/lava change. So my fork is apparently "26 commits ahead of lava-nc/lava:main with 0 files changed"

**Review by mgkwill — CHANGES_REQUESTED** [review]
We should clean our forks by force pushing to them if necessary.

**Comment by mgkwill** [comment]
For posterity, one way to clean your fork :
```
$ git status      # make sure you are on branch you want to fix, main in this case
$ git remote -v   # for this to work you need an upstream remote, git add remote upstream <url>

origin git@github.com:mgkwill/lava.git (fetch)
origin git@github.com:mgkwill/lava.git (push)
upstream git://github.com/lava-nc/lava.git (fetch)
upstream git://github.com/lava-nc/lava.git (push)

$ git fetch upstream
$ git reset --hard HEAD~10  ## WARNING DESTRUCTIVE Where 10 represents the number of commits that you want to clear

HEAD is now at dd6a09b Fix Packaging Bug (#30)

$ git pull upstream main
$ git push -f
```

**Comment by srrisbud** [comment]
> 

Thanks! 

I followed a slightly different version of this flow, which also happens to be non-destructive, based on a Stackoverflow answer: https://stackoverflow.com/a/7244456

```bash
# Add the remote, call it "upstream":

git remote add upstream https://github.com/whoever/whatever.git

# Fetch all the branches of that remote into remote-tracking branches

git fetch upstream

# Make sure that you're on your master branch:

git checkout master

# Rewrite your master branch so that any commits of yours that
# aren't already in upstream/master are replayed on top of that
# other branch:

git rebase upstream/master
git push -f origin master
```

**Pull request closed without merging**
