### PR TITLE
Move tutorials to root directory of the repo

### PR DESCRIPTION
**Pull request by bamsumit**
Signed-off-by: bamsumit <bam_sumit@hotmail.com>

### CODE REVIEW

**Comment by bamsumit** [comment]
There does not seem to be tutorial links in the Readme. The links in lava-nc.org needs to be fixed.

**Review by phstratmann — CHANGES_REQUESTED** [review]
Thanks for moving the tutorials! I would appreciate if you could adjust the links accordingly. We link to the tutorials here:
- the tutorials link to each other at various positions
- we link to them from the documentation on lava-nc.org -> getting started with Lava

**Comment by bamsumit** [comment]
> Thanks for moving the tutorials! I would appreciate if you could adjust the links accordingly. We link to the tutorials here:
> 
> * the tutorials link to each other at various positions
> * we link to them from the documentation on lava-nc.org -> getting started with Lava

Thanks for pointing that out. I already have a sprint checklist for it. I'll add one for tutorials as well. I'll create a separate issue and fix the links once this is merged. It's good to use the actual links rather than anticipate it beforehand.

**Action item after this merge**
* Fix link in lava-nc.org
* Fix link inside tutorials themselves

@phstratmann Did I miss anytihing?

**Review by phstratmann — CHANGES_REQUESTED** [review]
Thanks!
Could you just also change the links on lava-nc.org? To do so, you need to change them in the following file within the github:
lava-nc/lava-docs/getting_started_with_lava.rst

**Comment by bamsumit** [comment]
> Thanks! Could you just also change the links on lava-nc.org? To do so, you need to change them in the following file within the github: lava-nc/lava-docs/getting_started_with_lava.rst

Yes, that's fixed here: https://github.com/lava-nc/lava-docs/pull/16

**Review by phstratmann — APPROVED** [review]

**Review by mathisrichter — APPROVED** [review]
Looks good

**Pull request merged**
