### PR TITLE
Tutorial tests

### PR DESCRIPTION
**Pull request by mgkwill**
Issue Number: #243 

Objective of pull request: Create tests for tutorials

## Pull request checklist

Your PR fulfills the following requirements:
- [x] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
- [x] Tests are part of the PR (for bug fixes / features)
- [x] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
- [x] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [x] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
- [x] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
- [x] Build tests (`pytest`) passes locally

## Pull request type

 

 

Please check your PR type:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation changes
- [x] Other (please describe): Testing

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by mgkwill** [comment]
For whatever reason the CI is not pulling in new requirement nbconvert.

**Comment by mgkwill** [comment]
Looking into it.

This passes locally.

**Comment by mgkwill** [comment]
My mistake. It looks like nbconvert was not part of dependencies. It is now.

**Review by joyeshmishra — APPROVED** [review]

**Review by PhilippPlank — APPROVED** [review]
This is a great idea to keep our tutorials alive.

**Comment by mgkwill** [comment]
Due to path issues I couldn't get this to run on windows and I don't have time to debug right now. I've excluded other OSes besides Linux for now. Having fast feedback on Linux is a good start and should catch 99% of issues we would see that break our tutorials.

We can revisit windows and mac OS at a later date.

**Pull request merged**
