### PR TITLE
Fix Packaging Bug

### PR DESCRIPTION
**Pull request by mgkwill**
It appears that pybuilder needs a top level src dir before python modules to correctly build.

Pointing pybuilder to 'lava' as the source directory, it assumes this directory is not part of the src and only processes the directories below this ignoring the __init__.py 

The solution for now seems to be to add a src directory above lava and specify 'src' as the build path.

This pull request changes lava dir structure and updates pybuilder to create usable install artifacts.

This change adds `src/` to lava src path.

### Old Directory Structure:
```
.
├── docs
├── lava
│   ├── magma
│   ├── proc
│   ├── tutorials
│   └── utils
├── scripts
└── tests
    └── magma
```

### New Directory Structure:
```
.
├── docs
├── scripts
├── src
│   └── lava
│       ├── magma
│       ├── proc
│       ├── tutorials
│       └── utils
└── tests
    └── lava
        └── magma
```

### New Release Artifact Directory Structure:
```
lava-nc-0.1.0/
├── lava
│   ├── __init__.py
│   ├── magma
│   ├── proc
│   ├── tutorials
│   └── utils
├── lava_nc.egg-info
│   ├── dependency_links.txt
│   ├── namespace_packages.txt
│   ├── PKG-INFO
│   ├── requires.txt
│   ├── SOURCES.txt
│   ├── top_level.txt
│   └── zip-safe
├── PKG-INFO
├── setup.cfg
└── setup.py
```

I've tested both source and install artifact with this change and can install with `pip install lava-nc-0.1.0.tar.gz` and `pip install .` at top level dir structure.

Also I can `import lava`, `import lava.magma` using the above install into a venv.

**With the release artifact:**
```
$ python3 -m venv 2l-venv
$ . 2l-venv/bin/activate
$ wget https://github.com/lava-nc/lava/releases/download/v0.1.0/lava-nc-0.1.0.tar.gz

...

$ pip install lava-nc-0.1.0.tar.gz

Processing ./lava-nc-0.1.0.tar.gz
Collecting pytest
  Using cached pytest-6.2.5-py3-none-any.whl (280 kB)
Collecting unittest2
  Using cached unittest2-1.1.0-py2.py3-none-any.whl (96 kB)
...
Using legacy 'setup.py install' for lava-nc, since package 'wheel' is not installed.
Installing collected packages: six, pyparsing, linecache2, traceback2, toml, python-dateutil, py, pluggy, pillow, packaging, numpy, kiwisolver, iniconfig, cycler, attrs, argparse, unittest2, pytest, matplotlib, lava-nc
    Running setup.py install for lava-nc ... done
Successfully installed argparse-1.4.0 attrs-21.2.0 cycler-0.11.0 iniconfig-1.1.1 kiwisolver-1.3.2 lava-nc-0.1.0 linecache2-1.0.0 matplotlib-3.4.3 numpy-1.21.4 packaging-21.2 pillow-8.4.0 pluggy-1.0.0 py-1.11.0 pyparsing-2.4.7 pytest-6.2.5 python-dateutil-2.8.2 six-1.16.0 toml-0.10.2 traceback2-1.4.0 unittest2-1.1.0

$ python3

[GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lava
>>> import lava.magma
>>> quit()

$ pip uninstall lava-nc

Found existing installation: lava-nc 0.1.0
Uninstalling lava-nc-0.1.0:
  Would remove:
    /lava/2l-venv/lib/python3.9/site-packages/lava/*
    /lava/2l-venv/lib/python3.9/site-packages/lava_nc-0.1.0-py3.9.egg-info
Proceed (y/n)? y
  Successfully uninstalled lava-nc-0.1.0
```

### CODE REVIEW

**Comment by mgkwill** [comment]
Do we need to separate by  language? If not we can remove the `src/python` in the new dir structure.

**Comment by awintel** [comment]
We will definitely have C/C++ down the road as we migrate the Lava-on-Loihi code into the public. 
Question is, should we integrate that into the existing directory structure or branch it at the root level into different c, cpp, python directories?

**Comment by awintel** [comment]
I'd prefer :
/lava-nc/lava|||src/lava/python
/lava-nc/lava|||src/lava/python/magma/...
/lava-nc/lava|||src/lava/python/proc/...
/lava-nc/lava|||src/lava/python/utils/...
/lava-nc/lava|||src/lava/python/tutorials/...
/lava-nc/lava|||src/lava/__init__.py # bypasses /python
/lava-nc/lava|||src/lava/c
/lava-nc/lava|||src/lava/cpp

... because then there is one clear /lava root after the pybuilder-required /src

**Comment by mgkwill** [comment]
> I'd prefer : /lava-nc/lava|||src/lava/python/magma/... /lava-nc/lava|||src/lava/python/proc/... /lava-nc/lava|||src/lava/python/utils/... /lava-nc/lava|||src/lava/python/tutorials/... /lava-nc/lava|||src/lava/**init**.py # bypasses /python /lava-nc/lava|||src/lava/c /lava-nc/lava|||src/lava/cpp /lava-nc/lava|||tests/...
> 
> ... because then there is one clear /lava root after the pybuilder-required /src
> 
> /lava-nc/lava|||src/lava/ ... is what people would put on their PYTHONPATH after cloning.
> 
> Be sure to update install instructions once we make any change.

Changed to match @awintel proposed path except excluding final `python`

/lava-nc/lava|||src/lava/

If feels like we should add `python` and `__init__.py` at a later date, as it does not appear trivial creating an `__init__.py` that imports sub packages of `src/lava/python` but leaves the namespace as `lava.magma`, perhaps this can be a follow on change.

Relative path at top of repo for now is:
```
.
├── docs
├── scripts
├── src
│   └── lava
│       ├── magma
│       ├── proc
│       ├── tutorials
│       └── utils
└── tests
    └── lava
        └── magma
```

**Review by joyeshmishra — APPROVED** [review]

**Comment by mgkwill** [comment]
@joyeshmishra Thanks for the review.

**Review by awintel — APPROVED** [review]
Hope it all works.

**Pull request merged**
